const FOOD_AUDIO_FILES: Record<'en' | 'pt' | 'es', Record<string, number>> = {
  en: {
    apple: require('./en/food/Apple_.mp3'),
    avocado: require('./en/food/Avocado_.mp3'),
    banana: require('./en/food/Banana_.mp3'),
    beans: require('./en/food/Beans_.mp3'),
    bread: require('./en/food/Bread_.mp3'),
    cake: require('./en/food/Cake_.mp3'),
    carrot: require('./en/food/Carrot_.mp3'),
    cheese: require('./en/food/Cheese_.mp3'),
    corn: require('./en/food/Corn_.mp3'),
    egg: require('./en/food/Egg_.mp3'),
    fries: require('./en/food/French_fries_.mp3'),
    hamburger: require('./en/food/Hamburger_.mp3'),
    icecream: require('./en/food/Ice_cream_.mp3'),
    milk: require('./en/food/Milk_.mp3'),
    orange: require('./en/food/Orange_.mp3'),
    pineapple: require('./en/food/Pineapple_.mp3'),
    pizza: require('./en/food/Pizza_.mp3'),
    popcorn: require('./en/food/Popcorn_.mp3'),
    potato: require('./en/food/Potato_.mp3'),
    salad: require('./en/food/Salad_.mp3'),
    strawberry: require('./en/food/Strawberry_.mp3'),
    watermelon: require('./en/food/Watermelon_.mp3'),
  },
  pt: {
    apple: require('./pt/food/Apple_.mp3'),
    avocado: require('./pt/food/Avocado_.mp3'),
    banana: require('./pt/food/Banana_.mp3'),
    beans: require('./pt/food/Beans_.mp3'),
    bread: require('./pt/food/Bread_.mp3'),
    cake: require('./pt/food/Cake_.mp3'),
    carrot: require('./pt/food/Carrot_.mp3'),
    cheese: require('./pt/food/Cheese_.mp3'),
    corn: require('./pt/food/Corn_.mp3'),
    egg: require('./pt/food/Egg_.mp3'),
    fries: require('./pt/food/French_fries_.mp3'),
    hamburger: require('./pt/food/Hamburger_.mp3'),
    icecream: require('./pt/food/Ice_cream_.mp3'),
    milk: require('./pt/food/Milk_.mp3'),
    orange: require('./pt/food/Orange_.mp3'),
    pineapple: require('./pt/food/Pineapple_.mp3'),
    pizza: require('./pt/food/Pizza_.mp3'),
    popcorn: require('./pt/food/Popcorn_.mp3'),
    potato: require('./pt/food/Potato_.mp3'),
    salad: require('./pt/food/Salad_.mp3'),
    strawberry: require('./pt/food/Strawberry_.mp3'),
    watermelon: require('./pt/food/Watermelon_.mp3'),
  },
  es: {
    apple: require('./es/food/Apple_.mp3'),
    avocado: require('./es/food/Avocado_.mp3'),
    banana: require('./es/food/Banana_.mp3'),
    beans: require('./es/food/Beans_.mp3'),
    bread: require('./es/food/Bread_.mp3'),
    cake: require('./es/food/Cake_.mp3'),
    carrot: require('./es/food/Carrot_.mp3'),
    cheese: require('./es/food/Cheese_.mp3'),
    corn: require('./es/food/Corn_.mp3'),
    egg: require('./es/food/Egg_.mp3'),
    fries: require('./es/food/French_fries_.mp3'),
    hamburger: require('./es/food/Hamburger_.mp3'),
    icecream: require('./es/food/Ice_cream_.mp3'),
    milk: require('./es/food/Milk_.mp3'),
    orange: require('./es/food/Orange_.mp3'),
    pineapple: require('./es/food/Pineapple_.mp3'),
    pizza: require('./es/food/Pizza_.mp3'),
    popcorn: require('./es/food/Popcorn_.mp3'),
    potato: require('./es/food/Potato_.mp3'),
    salad: require('./es/food/Salad_.mp3'),
    strawberry: require('./es/food/Strawberry_.mp3'),
    watermelon: require('./es/food/Watermelon_.mp3'),
  },
};

export default FOOD_AUDIO_FILES;
